### ISSUE TITLE
[Question] Issue with microphone on BigSur OC

### ISSUE THREAD

**Issue by schmosbyy** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh#34]
I originally had the layout-id set to "13" however the mic volume was very low and slightly noisy.
In order to fix that, i tried changing the layout-id to "3", this helped immensly as now th mic sound was crystal clear, however now whenever I put the laptop to sleep and wake it up, the mic stops working unless it is restarted.
I have tried injecting CodecCommander even at EFI. 
Can you please suggest what else can be done? Or would there be a way to increase the sound for layout-id"13" since it works perfectly even after sleep.
I have read at multiple places that VoodoHDA will work, but it is not recommended, hence would like to find a way of using Lilu+AppleALC

**Comment by whatnameisit** [comment]
There's a reason I made an issue template. You provide no proof of low volume and noise.
CodecCommander was the only way to make the mic work with layout-id 3 when it is installed in /L/E. It is now deprecated in favor of layout-13 and bootloader injection of kexts. So I don't believe you saying the mic works with layout-id of 3 with the way you installed CodecCommander.
Look into the System Preferences and increase the sound input level and see if that helps with low volume. As for the noise, if there really is one, write a fix in AppleALC or PM people who wrote the layout-id 13. AppleALC Instructions: https://github.com/F0x1c/AppleALC_Instructions. Layout-id 13 creators: https://github.com/acidanthera/AppleALC/commits/master/Resources/CX8050.
